const argon2 = require('argon2');
const bcrypt = require('bcryptjs');

// Configuration for Argon2id hashing
const ARGON2_OPTIONS = {
  type: argon2.argon2id,
  memoryCost: 65536, // 64 MB
  timeCost: 3,       // 3 iterations
  parallelism: 4     // 4 parallel threads
};

/**
 * Hash a plain text password using Argon2id.
 * @param {string} password - The plain text password.
 * @returns {Promise<string>} The Argon2id hashed password.
 */
const hashPassword = async (password) => {
  return await argon2.hash(password, ARGON2_OPTIONS);
};

/**
 * Check if the given hash string is generated by Argon2.
 * Argon2 hashes usually begin with '$argon2' (e.g., $argon2id$...).
 * @param {string} hash - The password hash to check.
 * @returns {boolean} True if it is an Argon2 hash.
 */
const isArgon2Hash = (hash) => {
  return typeof hash === 'string' && hash.startsWith('$argon2');
};

/**
 * Compare a plain text password with a stored hash.
 * Automatically handles verification using Argon2id or legacy bcrypt.
 * @param {string} password - The plain text password.
 * @param {string} hash - The stored password hash.
 * @returns {Promise<boolean>} True if the password matches the hash.
 */
const comparePassword = async (password, hash) => {
  if (isArgon2Hash(hash)) {
    try {
      return await argon2.verify(hash, password);
    } catch (error) {
      // Log or handle verify errors safely without exposing secrets
      return false;
    }
  } else {
    // Fallback to legacy bcrypt
    return await bcrypt.compare(password, hash);
  }
};

module.exports = {
  hashPassword,
  isArgon2Hash,
  comparePassword
};
